FROM nvcr.io/nvidia/tritonserver:23.05-py3

LABEL maintainer="NVIDIA"
LABEL repository="tritonserver"

ENV TZ=UTC \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get -y install swig && apt-get -y install python3-dev && apt-get install -y cmake

RUN pip install --upgrade pip
RUN pip install torch==2.2.2+cu121 torchaudio==2.2.2+cu121 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install https://huggingface.co/csukuangfj/kaldifeat/resolve/main/cuda/1.25.5.dev20241029/linux/kaldifeat-1.25.5.dev20250203+cuda12.1.torch2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
RUN pip install pyyaml onnx

RUN git clone https://github.com/Slyne/ctc_decoder.git && cd ctc_decoder/swig && bash setup.sh
COPY ./scripts scripts
